### ISSUE TITLE
User Id prompt?

### ISSUE THREAD

**Issue by dinosaw** [Entrivax/extractor#51]
Once I have browsed to the OF model page I'm wanting to extract data for, I run the Node application successfully, which then gives me the code to put into the Web console. After running the code, I get prompted for a "user id". What is this? Is this my username? Is this the OF model's username? Is this my email address?

I assumed it was my username so I put that in, but it basically just logs me out of the OF page and puts me back at the login page with the infobox at the top right saying download in progress but nothing happens. Is it supposed to take you to the login page while extracting data?

**Comment by Entrivax** [comment]
Yeah, no, it was your own user id, it is a number. The prompt was added as a workaround when OF modified their API, with an endpoint not working as expected. I just pushed a fix removing the prompt, querying automatically the user id needed.

> Is it supposed to take you to the login page while extracting data?
Nope, but it was done probably because of an incorrect user id, OF disconnecting your session because of that.

So, now, you can pull the last commit, and it should work as expected. If you have any other question, don't hesitate to ask!
